In [12]:
import pandas as pd
import numpy as np
import os

In [13]:
# load results (will be added to)
root = os.getcwd()
trans_DF = pd.read_csv(root + '/nab/Data/trans_DF.csv').iloc[:,1:]
test_DF = trans_DF[trans_DF.test == 1].reset_index(drop = True).drop('fileloc', axis = 1)

print(test_DF.shape) # true labels

(8412, 11)

In [14]:
test_DF[0:10]

,label,P1,P2,P3,P4,control,gender,word,train,dev,test
0,CM13_B1_C1_M3,CM13,B1,C1,M3,1,M,command,0,0,1
1,CM13_B1_C1_M5,CM13,B1,C1,M5,1,M,command,0,0,1
2,CM13_B1_C1_M6,CM13,B1,C1,M6,1,M,command,0,0,1
3,CM13_B1_C1_M7,CM13,B1,C1,M7,1,M,command,0,0,1
4,CM13_B1_C1_M8,CM13,B1,C1,M8,1,M,command,0,0,1
5,CM13_B1_C10_M3,CM13,B1,C10,M3,1,M,line,0,0,1
6,CM13_B1_C10_M5,CM13,B1,C10,M5,1,M,line,0,0,1
7,CM13_B1_C10_M6,CM13,B1,C10,M6,1,M,line,0,0,1
8,CM13_B1_C10_M7,CM13,B1,C10,M7,1,M,line,0,0,1
9,CM13_B1_C10_M8,CM13,B1,C10,M8,1,M,line,0,0,1

# Google

In [15]:
goog_results = pd.read_csv(root + '/nab/Results/goog_results.csv', ).iloc[:,1:]
goog_results[0:5]

             label transcript
0   M14_B3_CW72_M8         go
1  CM13_B2_UW98_M3       ring
2   F04_B1_UW85_M5  telephone
3   M16_B3_CW42_M8        NaN
4   M14_B1_UW71_M5   gigantic

In [16]:
# merge with google
goog_results = test_DF.merge(goog_results, how = 'inner', on = 'label')

# convert nubmers to spelling
nums = {'0': 'zero', '1': 'one', '2': 'two', '3': 'three', '4': 'four', '5': 'five', '6': 'six', '7': 'seven', '8': 'eight', '9': 'nine'}
for num,spell in nums.items():
    goog_results.loc[goog_results.transcript == num, 'transcript'] = spell

In [20]:
goog_results = goog_results.assign(correct = np.where(goog_results.word == goog_results.transcript, 1, 0))

In [32]:
print('Google accuracy on speakers with dyarthria: ', goog_results[goog_results.control == 1].correct.mean() * 100, '%', sep = '')
print('Google accuracy on speakers without dyarthria: ', goog_results[goog_results.control == 0].correct.mean() * 100, '%', sep = '')

Google accuracy on speakers with dyarthria: 84.52287581699346%
Google accuracy on speakers without dyarthria: 48.245040331371264%